# Generated by Django 4.1.6 on 2023-02-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0002_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
