# Generated by Django 4.1.6 on 2023-02-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0004_alter_ocorrencia_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ocorrencia',
            new_name='Transacao',
        ),
    ]
